[{"kind": "Listing", "data": {"modhash": "", "children": [{"kind": "t3", "data": {"contest_mode": false, "banned_by": null, "media_embed": {}, "subreddit": "Python", "selftext_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I wrote some methods which were tagged @numba.jit() and in my development conda environment everything worked fine. However when I went to test the module I am working on in another environment it threw the following error (which incidentally I have found happens in all of my environments except that development environment and happens at import of numba)&lt;/p&gt;\n\n&lt;p&gt;Throwing the error:&lt;/p&gt;\n\n&lt;pre&gt;&lt;code&gt;(ML3) **EliasFlint**@MorallyAmbiguousHighHorse ~/Programming/packages/astroSynth $: python -c &amp;quot;import numba&amp;quot;\n&lt;/code&gt;&lt;/pre&gt;\n\n&lt;p&gt;Error:&lt;/p&gt;\n\n&lt;pre&gt;&lt;code&gt;Traceback (most recent call last):\nFile &amp;quot;&amp;lt;string&amp;gt;&amp;quot;, line 1, in &amp;lt;module&amp;gt;\nFile &amp;quot;/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/__init__.py&amp;quot;, line 12, in &amp;lt;module&amp;gt;\n  from .special import typeof\nFile &amp;quot;/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/special.py&amp;quot;, line 3, in &amp;lt;module&amp;gt;\n  from .typing.typeof import typeof\nFile &amp;quot;/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/typing/__init__.py&amp;quot;, line 2, in &amp;lt;module&amp;gt;\n  from .context import BaseContext, Context\nFile &amp;quot;/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/typing/context.py&amp;quot;, line 10, in &amp;lt;module&amp;gt;\n  from numba.typeconv import Conversion, rules\nFile &amp;quot;/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/typeconv/rules.py&amp;quot;, line 3, in &amp;lt;module&amp;gt;\n  from .typeconv import TypeManager, TypeCastingRules\nFile &amp;quot;/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/typeconv/typeconv.py&amp;quot;, line 3, in &amp;lt;module&amp;gt;\n  from . import _typeconv, castgraph, Conversion\nImportError: /home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-   packages/numba/typeconv/_typeconv.cpython-36m-x86_64-linux-gnu.so:       undefined symbol: __cxa_throw_bad_array_new_length\n&lt;/code&gt;&lt;/pre&gt;\n\n&lt;p&gt;I&amp;#39;ve tried going threw and matching all the package versions from my development environment to my working environment and that did not yield any useful results, so I am at a loss? thanks.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;", "selftext": "I wrote some methods which were tagged @numba.jit() and in my development conda environment everything worked fine. However when I went to test the module I am working on in another environment it threw the following error (which incidentally I have found happens in all of my environments except that development environment and happens at import of numba)\n\nThrowing the error:\n\n    (ML3) **EliasFlint**@MorallyAmbiguousHighHorse ~/Programming/packages/astroSynth $: python -c \"import numba\"\nError:\n\n    Traceback (most recent call last):\n    File \"&lt;string&gt;\", line 1, in &lt;module&gt;\n    File \"/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/__init__.py\", line 12, in &lt;module&gt;\n      from .special import typeof\n    File \"/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/special.py\", line 3, in &lt;module&gt;\n      from .typing.typeof import typeof\n    File \"/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/typing/__init__.py\", line 2, in &lt;module&gt;\n      from .context import BaseContext, Context\n    File \"/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/typing/context.py\", line 10, in &lt;module&gt;\n      from numba.typeconv import Conversion, rules\n    File \"/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/typeconv/rules.py\", line 3, in &lt;module&gt;\n      from .typeconv import TypeManager, TypeCastingRules\n    File \"/home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-packages/numba/typeconv/typeconv.py\", line 3, in &lt;module&gt;\n      from . import _typeconv, castgraph, Conversion\n    ImportError: /home/**EliasFlint**/.conda/envs/ML3/lib/python3.6/site-   packages/numba/typeconv/_typeconv.cpython-36m-x86_64-linux-gnu.so:       undefined symbol: __cxa_throw_bad_array_new_length\n\nI've tried going threw and matching all the package versions from my development environment to my working environment and that did not yield any useful results, so I am at a loss? thanks.", "likes": null, "suggested_sort": null, "user_reports": [], "secure_media": null, "link_flair_text": null, "id": "65qtfc", "gilded": 0, "secure_media_embed": {}, "clicked": false, "score": 3, "report_reasons": null, "author": "EliasFlint", "saved": false, "mod_reports": [], "name": "t3_65qtfc", "subreddit_name_prefixed": "r/Python", "approved_by": null, "over_18": false, "domain": "self.Python", "hidden": false, "thumbnail": "", "subreddit_id": "t5_2qh0y", "edited": false, "link_flair_css_class": null, "author_flair_css_class": null, "downs": 0, "brand_safe": true, "archived": false, "removal_reason": null, "is_self": true, "hide_score": false, "spoiler": false, "permalink": "/r/Python/comments/65qtfc/numba_import_error_undefined_symbol_cxa_throw_bad/", "num_reports": null, "locked": false, "stickied": false, "created": 1492398717.0, "url": "https://www.reddit.com/r/Python/comments/65qtfc/numba_import_error_undefined_symbol_cxa_throw_bad/", "author_flair_text": null, "quarantine": false, "title": "Numba Import error, \u201cundefined symbol: __cxa_throw_bad_array_new_length\u201d", "created_utc": 1492369917.0, "distinguished": null, "media": null, "upvote_ratio": 0.66, "num_comments": 1, "visited": false, "subreddit_type": "public", "ups": 3}}], "after": null, "before": null}}, {"kind": "Listing", "data": {"modhash": "", "children": [{"kind": "t1", "data": {"subreddit_id": "t5_2qh0y", "removal_reason": null, "link_id": "t3_65qtfc", "likes": null, "replies": "", "user_reports": [], "id": "dgcqtdo", "gilded": 0, "archived": false, "score": 1, "report_reasons": null, "author": "Fylwind", "parent_id": "t3_65qtfc", "subreddit_name_prefixed": "r/Python", "controversiality": 0, "body": "I don't know what's going on, but judging from the [top Google result](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71757), the missing symbol appears to be from libstdc++ (the C++ standard library for GCC). The symbol was introduced fairly recently (GCC 6.1.0), which suggests that it appears your Numba library was compiled using a newer compiler, but when you loaded the library in Python it tried to use an older version of libstdc++.  Do you happen to have multiple versions of GCC installed?", "edited": false, "downs": 0, "body_html": "&lt;div class=\"md\"&gt;&lt;p&gt;I don&amp;#39;t know what&amp;#39;s going on, but judging from the &lt;a href=\"https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71757\"&gt;top Google result&lt;/a&gt;, the missing symbol appears to be from libstdc++ (the C++ standard library for GCC). The symbol was introduced fairly recently (GCC 6.1.0), which suggests that it appears your Numba library was compiled using a newer compiler, but when you loaded the library in Python it tried to use an older version of libstdc++.  Do you happen to have multiple versions of GCC installed?&lt;/p&gt;\n&lt;/div&gt;", "subreddit": "Python", "name": "t1_dgcqtdo", "score_hidden": false, "stickied": false, "created": 1492413736.0, "created_utc": 1492384936.0, "depth": 0, "mod_reports": [], "subreddit_type": "public", "ups": 1}}], "after": null, "before": null}}]